### ISSUE TITLE
Runtime error in IE10

### ISSUE THREAD

**Issue by lephuongbac** [bobril/bobx#1]
https://github.com/bobril/bobx/blob/06f85b72df8dd0e45439599f15717e5f75a48794/index.ts#L209

I can't use bobx in IE10 because this function use Map class of ES6.

Error:
'Map' is undefined

Bobx version: 0.12.2

**Comment by Bobris** [comment]
Currently we support only IE11+, so if you need IE10 support it will need polyfill.
