### ISSUE TITLE
nested arrays in bobx store always return incorrect value

### ISSUE THREAD

**Issue by lephuongbac** [bobril/bobx#2]
```
import { observable } from "bobx";
import * as b from "bobril";

interface IDialogData {
    content?: string[];
}
class SimpleStore {
    @observable
    data: IDialogData;
    initData() {
        this.data = {
            content: ["a", "b"]
        };
    }
}

var store = new SimpleStore();

b.init(() => {
    store.initData();
    console.log(store.data.content);
    return {
        tag: "p",
        children: ["content", store.data.content]
    };
});

```

Hi Boris,

store.data.content display in browser as empty.
`console.log(store.data.content);` returns `ObservableArray {$enhancer: ƒ, $atom: ObservableValue, $bobx: `Array(2)}

Is it bug?

**Comment by Bobris** [comment]
More like missing feature. Bobril really understands just array which returns true from Array.isArray. What you can do is `(store.data.content as any as ObservableArray<string>).toJS()` or slightly less kosher, but faster `(store.data.content as any as ObservableArray<string>).toJSON()`

Will think about adding direct support to Bobril, it is not free performance wise.

**Comment by lephuongbac** [comment]
we can't fix it in bobx? 
because store.data.content should returns string[] instead of ObservableArray<string>?

**Comment by Bobris** [comment]
By default `@observable` is "deep". You can "fix" this by using `@observable.shallow` instead, but of course after that changing that array will not invalidate bobril anymore... This is really missing feature in Bobril, nothing to change in Bobx.

**Comment by Bobris** [comment]
BTW: This link shows that Mobx 4 has same problem https://github.com/mobxjs/mobx#mobx-4-vs-mobx-5. Unfortunately Bobx cannot use Proxies because we have to support IE11.

**Comment by Bobris** [comment]
Implemented this in latest Bobril and Bobx.
